export const GET_PERSON_DATA_REQUEST="GET_PERSON_DATA_REQUEST";
export const GET_PERSON_DATA_SUCCESS="GET_PERSON_DATA_SUCCESS";
export const GET_PERSON_DATA_FAILURE="GET_PERSON_DATA_FAILURE";
export const GET_TEAM_DATA_SUCCESS ="GET_TEAM_DATA_SUCCESS";